### ISSUE TITLE
4-way buttons not working in note/dictionary

### ISSUE THREAD

**Issue by blchinezu** [blchinezu/pocketbook-coolreader#17]
http://www.mobileread.com/forums/showpost.php?p=3061786&postcount=22

"Now I see: the 4-way button on the PB Mini does not work at all in both note and dictionary mode. "

**Comment by blchinezu** [comment]
**pkb:**
"brucelee, you've modified CRPbCommands enumerations by inserting new commands into the middle and did not update keydefs.ini file. It could cause problems because old commands from keydefs.ini handled as new commands in the code. "

**Comment by maslukov** [comment]
He wrote about the problem here:
http://www.the-ebook.org/forum/viewtopic.php?p=1225898#1225898

google translate:
"There is a list of commands, he added to this list (in the middle), several new teams, as a result of the value (s) for the old commands have changed. When this file is not updated keydefs.ini. Hence instead of the old team is trying to meet the new, that for older models just are not supported. And the old steel unknown. If he would have added a new team in the bottom of the list, the old-team continued to work, and you need to update keydefs.ini, to match the transfer CRPbCommands and in theory it should work."
