### ISSUE TITLE
not working on PB650: No book to open

### ISSUE THREAD

**Issue by doodle8866** [blchinezu/pocketbook-coolreader#186]
I tried to install the lateset release version "cr3-v0.0.6-17-48-pro5.zip" on my PB650(FW5.12). The app didn't even show up in the panel.  After I made a copy of "cr3-pb" to "/applications", the app finially shows but report "No book to open" when I try to execute it. 

Following is "cr3-pb.crash.log":

> Atached mp shm: id 0 addr 2ab55000 size 21568
> attach_shm: mtfb key=251333953 size=835220
> Atached mtfb shm: id 29000a addr 2caf6000 size 835220
> -------------------------
> The task - cr3-pb.app have
>  xres=758 yres=1024 bpp=4 vdepth=8
> -------------------------
> ndepth:4 hqdepth:4 orientation:0
> attach_shm: ref key=2130378752 size=778240
> Atached ref shm: id 8001 addr 2cc58000 size 778240
> OpenTheme: /ebrmain/themes/Line.pbt
> Theme real name: Line
> ts: loading default calibration values
> Resourse 'dictionary_top' is not found
> Resourse 'dictionary_bottom' is not found

**Comment by blchinezu** [comment]
You shouldn't launch the app directly, it's only used from the library. After overwriting the extensions.cfg file (or updating it manually if you have custom things in it) it will automatically open your book with CR3.
The app doesn't have its own file browser so you can select the book you want to open that's why it doesn't show up in the apps menu.
